site_name: Cloud Native Abidjan
site_description: Cloud Native Abidjan — Learn • Share • Build • Together
site_url: https://cloud-native-abidjan.github.io/community-docs/

theme:
  name: material
  language: fr
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tooltips
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Mode clair

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      zoomable: true

extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      name: Cloud Native Abidjan sur LinkedIn
      link: https://www.linkedin.com/company/cloud-native-abidjan/
    - icon: fontawesome/brands/github
      name: Cloud Native Abidjan sur GitHub
      link: https://github.com/Cloud-Native-Abidjan
    - icon: fontawesome/brands/whatsapp
      name: Groupe WhatsApp Cloud Native Abidjan
      link: https://chat.whatsapp.com/BqhizdWbC4e1lpPcJiCayW
    - icon: fontawesome/solid/envelope
      name: Contacter Cloud Native Abidjan par email
      link: mailto:cloudnativeabidjan@gmail.com

copyright: Cloud Native Abidjan

nav:
  - Accueil: index.md
  - Rejoindre la communauté: join-community.md
  - Événements: events.md
  - Communauté: community.md
  - Contact: contact.md
